#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🚧 Running npm run build before push..."
npm run build

if [ $? -ne 0 ]; then
  echo "Build failed. Push aborted."
  exit 1
fi

echo "Build succeeded. Proceeding with push."